### ISSUE TITLE
找不到prob_trans.json等文件

### ISSUE THREAD

**Issue by Joick** [1483523635/jieba.NetCore#5]
克隆了源码项目, 编译没问题, debug项目的时候, 执行"segmenter.LoadUserDict("userdict.txt");"时抛出找不到配置文件错误。
编译IDE:vs 2019 enterprise

**Comment by xiaoquisme** [comment]
感谢反馈。

本地clone 之后运行项目需要手动修改[Program.cs: line 15](https://github.com/1483523635/jieba.NetCore/blob/master/jieba.NET/Program.cs#L15) ,和[Program.cs: line 14](https://github.com/1483523635/jieba.NetCore/blob/master/jieba.NET/Program.cs#L14) 里描述的那样 你需要设置Resource路径。

### 修改方式：

> 进入解决方案的Segmenter 项目， 执行`pwd`(Mac / Linux), `dir`(windows) 查看路径
> 之后进行手动替换`AppDomain.CurrentDomain.SetData("JiebaConfigFileDir", <这里是你的resource 存放的路径>);` 

希望对你有帮助 有问题可以继续open这个issue。

**Comment by xiaoquisme** [comment]
刚刚进行了修改。 你可以拉取最新的代码，就能不用做任何修改，启动项目。但是你仍旧要去理解 resources的路径要手动去配置。

**Comment by Henxun** [comment]
你好，这个json文件里是需要放什么内容

**Comment by Joick** [comment]
I GOT IT...

**Comment by Henxun** [comment]
你got啥了？

**Comment by Henxun** [comment]
忽略我，我知道怎么回事了

**Comment by Joick** [comment]
I GOT IT...
